### ISSUE TITLE
ImageView

### ISSUE THREAD

**Issue by zhuhonglei** [CoderAlee/PaintedSkin#14]
第三方自定义控件中有ImageView,用的是setImageResource()设置的图片,这种情况,框架有办法适配吗?我看到框架里的ImageView只支持src属性

**Comment by CoderAlee** [comment]
> 第三方自定义控件中有ImageView,用的是setImageResource()设置的图片,这种情况,框架有办法适配吗?我看到框架里的ImageView只支持src属性

使用`WindowManager.getInstance().getWindowProxy(this).addEnabledThemeSkinView(ImageView, new SkinElement("src", R.drawable.xxx));` 就可以对ImageView通过setImageResource() 设置的属性进行换肤
