### ISSUE TITLE
点击换肤没反应 

### ISSUE THREAD

**Issue by kokobebekoko** [CoderAlee/PaintedSkin#18]
2021-12-15 16:17:03.180 28889-3254/org.alee.demo.skin E/.alee.demo.ski: Failed to open APK '/sdcard/night.skin' I/O error
2021-12-15 16:17:03.181 28889-3254/org.alee.demo.skin E/ThemeSkin: 无法获取到皮肤包包名 [ /sdcard/night.skin ]

**Comment by CoderAlee** [comment]
1. 请查看/sdcard/目录下是否存在night.skin 皮肤包
2. 请检查App是否有SDK读写权限

**Comment by kokobebekoko** [comment]
![图片](https://user-images.githubusercontent.com/5987097/146151224-fbaff146-d80f-42f3-a6d6-c337e069d137.png)
![图片](https://user-images.githubusercontent.com/5987097/146151299-62fafba6-f160-4bc2-84b9-02619b62147f.png)
![图片](https://user-images.githubusercontent.com/5987097/146151418-811aabad-4354-492b-b7a7-04157211c322.png)
![图片](https://user-images.githubusercontent.com/5987097/146151565-79a1f64c-a966-4446-b837-0f94cfda9d7b.png)

**Comment by CoderAlee** [comment]
麻烦提供一下测试设备的信息以及系统版本

**Comment by kokobebekoko** [comment]
> 麻烦提供一下测试设备的信息以及系统版本

HUAWEI Mate30 Android10 鸿蒙2.0.0

**Comment by CoderAlee** [comment]
如果是Android 10 及以上需要将night.skin 皮肤包Push 到 Context.getExternalFilesDir(null)?.absolutePath 这个目录下

**Comment by CoderAlee** [comment]
> > 麻烦提供一下测试设备的信息以及系统版本
> 
> HUAWEI Mate30 Android10 鸿蒙2.0.0

Android 10以上的系统已经不支持直接访问SD卡的目录了 所以不要注释掉
![image](https://user-images.githubusercontent.com/71973440/146152524-c55a7edb-8208-4ab5-86f0-f81cfbb84b29.png)
这段代码

**Comment by kokobebekoko** [comment]
> > > 麻烦提供一下测试设备的信息以及系统版本
> > 
> > 
> > HUAWEI Mate30 Android10 鸿蒙2.0.0
> 
> Android 10以上的系统已经不支持直接访问SD卡的目录了 所以不要注释掉 ![image](https://user-images.githubusercontent.com/71973440/146152524-c55a7edb-8208-4ab5-86f0-f81cfbb84b29.png) 这段代码

可以了 一开始没生成getExternalFilesDir文件夹 我也不知道为啥 后面才改了路径试一试

**Comment by CoderAlee** [comment]
> > > > 麻烦提供一下测试设备的信息以及系统版本
> > > 
> > > 
> > > HUAWEI Mate30 Android10 鸿蒙2.0.0
> > 
> > 
> > Android 10以上的系统已经不支持直接访问SD卡的目录了 所以不要注释掉 ![image](https://user-images.githubusercontent.com/71973440/146152524-c55a7edb-8208-4ab5-86f0-f81cfbb84b29.png) 这段代码
> 
> 可以了 一开始没生成getExternalFilesDir文件夹 我也不知道为啥 后面才改了路径试一试

OK 麻烦Close掉这条Issue 吧
