### ISSUE TITLE
debug模式下正常使用换肤功能，切换到relase模式下，报错了空指针了。

### ISSUE THREAD

**Issue by SoloLee** [CoderAlee/PaintedSkin#19]
怀疑是混淆引起的，请问这个库，有什么混淆规则需要添加吗？

**Comment by SoloLee** [comment]
使用的库如下
// 换肤核心库
    api 'com.github.CoderAlee.PaintedSkin:painted-skin:3.3.3'
    api 'com.github.CoderAlee.PaintedSkin:standard-plugin:3.3.3'
    api 'com.github.CoderAlee:Reflex:1.2.0'// 依赖的反射库
![image](https://user-images.githubusercontent.com/4515216/148325339-53439a93-4d10-4110-b45a-4222898dad7f.png)

**Comment by CoderAlee** [comment]
由于框架内对于部分系统API是通过反射进行访问的，所以部分代码不能被混淆。请先 keep 所有org.alee 开头的class，测试下是否为混淆所导致的崩溃，后续会增加混淆文档

**Comment by SoloLee** [comment]
嗯，感谢回复，已经搞定。-keep class org.alee.** {*;} 即正常。
