### ISSUE TITLE
引入gradle_plugin_android_aspectjx导致的运行崩溃

### ISSUE THREAD

**Issue by yihu5566** [CoderAlee/PaintedSkin#20]
这个是在gradle_plugin_android_aspectjx仓库下提交的问题

https://github.com/HujiangTechnology/gradle_plugin_android_aspectjx/issues/335

给后来的小伙伴一个参考和提示
最后感谢大佬开源精神。

**Comment by yihu5566** [comment]
我就直接关了啊

**Comment by CoderAlee** [comment]
Aspectjx 目前无法在kotlin 中做切面编程。是因为目前Gradle 在Transform 中无法获取到Kotlin的Class文件，所以无法对kotlin的Class进行切面.

**Comment by CoderAlee** [comment]
如果项目中的Application是使用Kotlin编写的，需要引用`StandardPlugin` 而非`AutoPlugin `

**Comment by carpediemvv** [comment]
> 如果项目中的Application是使用Kotlin编写的，需要引用`StandardPlugin` 而非`AutoPlugin `

没看明白这是什么意思？这个问题怎么解决呢

**Comment by CoderAlee** [comment]
> > 如果项目中的Application是使用Kotlin编写的，需要引用`StandardPlugin` 而非`AutoPlugin `
> 
> 没看明白这是什么意思？这个问题怎么解决呢

由于`AutoPlugin`是通过AOP的方式在Application的onCreate函数作为切入点实现的自动初始化，而目前AOP对于kotlin的支持还有问题，所以如果项目中的Application是使用Kotlin语言编写的，推荐使用`StandardPlugin `
