### ISSUE TITLE
TextView的drawableTopCompat属性

### ISSUE THREAD

**Issue by yihu5566** [CoderAlee/PaintedSkin#21]
目前发现TextView的drawableTopCompat属性设置drawable，资源无法更新。

` <TextView
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="5dp"
                    android:layout_weight="1"
                    android:drawablePadding="5dp"
                    android:gravity="center"
                    android:text="@string/profile_my_collect"
                    android:textColor="@color/profile_user_info_text_332F7466"
                    app:drawableTopCompat="@drawable/ic_profile_collect" />`

暂时我将图标和文字拆开了。
希望大佬有空看一下。谢谢了

**Comment by CoderAlee** [comment]
> 目前发现TextView的drawableTopCompat属性设置drawable，资源无法更新。
> 
> ` <TextView android:layout_width="0dp" android:layout_height="wrap_content" android:layout_marginStart="5dp" android:layout_weight="1" android:drawablePadding="5dp" android:gravity="center" android:text="@string/profile_my_collect" android:textColor="@color/profile_user_info_text_332F7466" app:drawableTopCompat="@drawable/ic_profile_collect" />`
> 
> 暂时我将图标和文字拆开了。 希望大佬有空看一下。谢谢了

目前是不支持`drawableTopCompat`属性换肤的，如果需要对TextView的`drawableTopCompat` 属性进行换肤可以参考文档第四章**支持自定义View、三方库提供的View、自定义属性换肤** 通过实现`IThemeSkinExecutorBuilder `接口对`drawableTopCompat` 提供支持

**Comment by yihu5566** [comment]
明白了，非常感谢🙏
