### ISSUE TITLE
大佬能否DEMO增加一个对第三方VIEW的示例。

### ISSUE THREAD

**Issue by fanqingwen** [CoderAlee/PaintedSkin#24]
说明里面的DefaultExecutorBuilder 实在不知道咋玩的

**Comment by CoderAlee** [comment]
前段时间比较忙，本周会增加对三方VIew的换肤支持示例与ExecutorBuilder扩展的示例

**Comment by CoderAlee** [comment]
Demo新增，SkinExecutorBuilder的使用示例
