### ISSUE TITLE
下载不下来

### ISSUE THREAD

**Issue by ylmyg** [CoderAlee/PaintedSkin#27]
请问下，我换来一台电脑，然后提示
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.CoderAlee.PaintedSkin:painted-skin:3.4.2.
     Searched in the following locations:

   > Could not find com.github.CoderAlee.PaintedSkin:standard-plugin:3.4.2.
请问该怎么办

**Comment by CoderAlee** [comment]
> 请问下，我换来一台电脑，然后提示
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Could not find com.github.CoderAlee.PaintedSkin:painted-skin:3.4.2.
> > Searched in the following locations:
> 
> > Could not find com.github.CoderAlee.PaintedSkin:standard-plugin:3.4.2.
> > 请问该怎么办

请使用最新版本3.5.1.+
