### ISSUE TITLE
AppCompatDialog 换肤失效

### ISSUE THREAD

**Issue by JiayuanChan** [CoderAlee/PaintedSkin#33]
使用AppCompatDialog时，报The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's。且不会执行换肤

**Comment by CoderAlee** [comment]
麻烦贴一下Dilaog的代码

**Comment by CoderAlee** [comment]
> 使用AppCompatDialog时，报The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's。且不会执行换肤

已增加示例程序。AppCompatDialog可正常换肤。
