### ISSUE TITLE
单Activity+多Fragment

### ISSUE THREAD

**Issue by JiayuanChan** [CoderAlee/PaintedSkin#39]
应用采用单Activity+多Fragment实现，使用Navigation 管理碎片，有没有针对Fragment的BaseWindowProxy

**Comment by CoderAlee** [comment]
设计时考虑到Fragment 存在多级嵌套，会有一个父Fragment 与多个子Fragment （甚至更深的层级）同时显示。当一个View被创建后难以判断其属于哪个Fragment 内。故没有针对Fragment的BaseWindowProxy。

**Comment by CoderAlee** [comment]
如果您有好的方案，可以提出，我们共通探讨。或实现后发起margeRequest
