### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by MYaoDan** [CoderAlee/PaintedSkin#40]
请大佬能否加个联系方式，我调试了半夜，一直是闪退，QQ1197933817，请求大佬帮助一下

**Comment by CoderAlee** [comment]
![image](https://github.com/CoderAlee/PaintedSkin/assets/71973440/2dbb8cc8-695f-426a-8551-d625deee8502)
建议您加入线上聊天室进行交流

**Comment by MYaoDan** [comment]
打不开，大佬，加下QQ吧，有偿，只要能解决问题，

**Comment by CoderAlee** [comment]
昨天有添加你的QQ，通过一下。或者你加我QQ 1551886674
