### ISSUE TITLE
ConstraintLayout怎么换肤啊？

### ISSUE THREAD

**Issue by csh159** [CoderAlee/PaintedSkin#44]
ConstraintLayoutCompat.init() 初始化了，配置的颜色没有哦效果！

**Comment by CoderAlee** [comment]
> ConstraintLayoutCompat.init() 初始化了，配置的颜色没有哦效果！

参照Demo工程对ConstraintLayout进行换肤。如果换肤的属性是background,初始化ConstraintLayoutCompat就可以了。

**Comment by csh159** [comment]
设置的是ConstraintLayout的背景background，主题也配置了黑色的，但是没效果，还是白色。
![1708312059936](https://github.com/CoderAlee/PaintedSkin/assets/4157414/0e8a8436-3503-439b-833d-5d988e1825e3)
![1708312090827](https://github.com/CoderAlee/PaintedSkin/assets/4157414/503d3376-9171-4e65-bc4e-b0a7174f63f6)

**Comment by csh159** [comment]
不知道为啥，有些页面切换就是不变化.....

**Comment by CoderAlee** [comment]
> 设置的是ConstraintLayout的背景background，主题也配置了黑色的，但是没效果，还是白色。 ![1708312059936](https://private-user-images.githubusercontent.com/4157414/305777395-0e8a8436-3503-439b-833d-5d988e1825e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjEzMDEsIm5iZiI6MTcwODMyMTAwMSwicGF0aCI6Ii80MTU3NDE0LzMwNTc3NzM5NS0wZThhODQzNi0zNTAzLTQzOWItODMzZC01ZDk4OGUxODI1ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDUzNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM5OGE2ZTk2MzQ1ZGNjZjcxZDJjOTg0YjVmZTBhMTI3Y2M2MWQ0MjUwYWY2NTY0NTQ0NGRhYmEyOWJiMjQ1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UIdUw5Ot_pdaNhqP1YrLBAof1SThf8p57ZI2_YJSURw) ![1708312090827](https://private-user-images.githubusercontent.com/4157414/305777562-503d3376-9171-4e65-bc4e-b0a7174f63f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjEzMDEsIm5iZiI6MTcwODMyMTAwMSwicGF0aCI6Ii80MTU3NDE0LzMwNTc3NzU2Mi01MDNkMzM3Ni05MTcxLTRlNjUtYmM0ZS1iMGE3MTc0ZjYzZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDUzNjQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ0MTlmNzg1ODk3YjJlNDYwM2QzNmU4ZDZlNmFkZGI1MmJiZDNjMzc0YzM4ODBhM2JlNDAyMGFjNTYzOWYyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zxycaQT2lyqtOuTBn_faFRduvA-b39QkGG5Hg5XjOWo)

皮肤包里有添加color_white属性么

**Comment by csh159** [comment]
加了的，同样color_white背景，有的页面有效，有的页面不变化。测试Demo新打开activity好像也有问题，不变化。新打开activity是不是有问题？

https://github.com/CoderAlee/PaintedSkin/assets/4157414/74bde525-1bd4-4184-be0b-32bdbfbb46ab

**Comment by CoderAlee** [comment]
> 加了的，同样color_white背景，有的页面有效，有的页面不变化。测试Demo新打开activity好像也有问题，不变化。新打开activity是不是有问题？ 默认用的白色 white_700
> 
> ![1708321712398](https://private-user-images.githubusercontent.com/4157414/305802020-358b13fd-8983-4bb7-a1bf-412afc75b5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjQ2NzcsIm5iZiI6MTcwODMyNDM3NywicGF0aCI6Ii80MTU3NDE0LzMwNTgwMjAyMC0zNThiMTNmZC04OTgzLTRiYjctYTFiZi00MTJhZmM3NWI1ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTlUMDYzMjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjk3Y2ViMzQyYTg4OGZjNThmY2EwNzY3ZmRkMDFmZTc1YzJlMGZlYWZiMDllNGQ5NDcxOTBiNWVjNzljYjMwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tSDI2RMpffRfp6EXud00nx4rK8wSLjKYgekBxTjzfmQ)
> 
>  9b85bb07a0c7dd0e582da3c7a73c8b16.mp4

方便的话可以加一下我的微信 
![9feae4fa1aed2ab863cb5f50f944279](https://github.com/CoderAlee/PaintedSkin/assets/71973440/cbef6285-8be4-4623-bd67-ff40941fec14)
