### ISSUE TITLE
Paint颜色可以支持吗？

### ISSUE THREAD

**Issue by HitaoLin** [CoderAlee/PaintedSkin#46]

**Comment by CoderAlee** [comment]
请提供Paint使用示例

**Comment by HitaoLin** [comment]
`                        val rect = Rect(left, top, right, bottom)
                        val paint = Paint()
                        paint.color = resources.getColor(R.color.color_red)
                        canvas.drawRect(rect,paint)`

**Comment by CoderAlee** [comment]
Demo中的org.alee.demo.skin.basic.ability.widget.CustomView 类有使用paint的示例代码，可以参阅

**Comment by HitaoLin** [comment]
![1716195570989](https://github.com/CoderAlee/PaintedSkin/assets/37434185/c633dd1a-f804-4f58-94a7-34f2553e5b92)

**Comment by CoderAlee** [comment]
支持换肤，可以参阅demo中对org.alee.demo.skin.basic.ability.widget.CustomView的换肤示例代码

**Comment by HitaoLin** [comment]
怎么随时更改paint颜色？

**Comment by CoderAlee** [comment]
paint.color =  ThemeSkinService.getInstance().currentThemeSkinPack.getColor(ResourceId)
invalidate()
