### ISSUE TITLE
Tablayout自定义Tab设置Textview的颜色切换无效

### ISSUE THREAD

**Issue by HitaoLin** [CoderAlee/PaintedSkin#47]
通过TabLayout.setCustomView()设置Tab的自定义view，自定义view是使用xml实现，TextView的textColor是使用selector实现，在其他皮肤下也添加了selector文件和color，切换皮肤textColor没有切换。
![1716261900301](https://github.com/CoderAlee/PaintedSkin/assets/37434185/2c2b3598-5b03-41fc-82b3-5c2ee44af3ca)
![1716261970968](https://github.com/CoderAlee/PaintedSkin/assets/37434185/22c652d6-7337-4f7b-921f-efd6cfc7d0da)

**Comment by CoderAlee** [comment]
TabLayout.setCustomView()的参数是在代码中动态创建的么？

**Comment by HitaoLin** [comment]
通过inflate获取view后,tablayout.setCustomView(view)

**Comment by CoderAlee** [comment]
> 通过inflate获取view后,tablayout.setCustomView(view)

1. 将Tab中TextView的textColor用在其他控件上确认是否能正确换肤。以排除是否为资源适配问题。
2. 确认LayoutInflate.from(context) 得到的inflate.factory2的值是什么？

**Comment by HitaoLin** [comment]
1.使用上边的selector文件在其他控件也无法换肤（使用了button进行修改textcolor）
2.打印出来是：factory2 = org.alee.component.skin.factory2.ThemeSkinFactory2@ae1a16b

**Comment by CoderAlee** [comment]
> 1.使用上边的selector文件在其他控件也无法换肤（使用了button进行修改textcolor） 2.打印出来是：factory2 = org.alee.component.skin.factory2.ThemeSkinFactory2@ae1a16b

资源在其他控件上也无法换肤，说明资源适配有问题，检查一下对应的皮肤包下是否有同名selector

**Comment by HitaoLin** [comment]
有同名的selector，把selector移到res/color就可以了
