### ISSUE TITLE
支持远程皮肤包动图下载更新吗？

### ISSUE THREAD

**Issue by MYaoDan** [CoderAlee/PaintedSkin#49]
可以将打包好的skin皮肤包上传到后台，然后下载解压进行修改皮肤吗？

**Comment by CoderAlee** [comment]
> 可以将打包好的skin皮肤包上传到后台，然后下载解压进行修改皮肤吗？

下载后只需要在IOptionFactory的requireOption中提供对应的IThemeSkinOption即可
