### ISSUE TITLE
欢迎页(windowSplashscreenContent)能够实现动态换肤吗?

### ISSUE THREAD

**Issue by zuilintan** [CoderAlee/PaintedSkin#5]

**Comment by CoderAlee** [comment]
如果你是通过在style文件中添加 <item name="android:windowSplashscreenContent">xxx</item> 来实现Splashscreen的话框架是无法支持动态替换的，因为这个属性是在PhoneWindowManager中被加载同时创建了SplashscreenView。
但如果你是有专门的Activity或Fragment来实现Splashscreen，那么框架是支持动态换肤的。

**Comment by zuilintan** [comment]
嗯, 看了下主流应用, 
QQ的夜间模式并未适配Splashscreen, 依然是亮色图片, 
知乎的夜间模式, Splashscreen会先显示亮色, 随后切换为暗色
