### ISSUE TITLE
自定义View的属性换肤到底怎么用

### ISSUE THREAD

**Issue by yxiangTang** [CoderAlee/PaintedSkin#53]
根据教程实现了IThemeSkinExecutorBuilder，自定义了ViewSkinExecutor，也addThemeSkinExecutorBuilder了，但是没有效果，debug也跑不进去

**Comment by CoderAlee** [comment]
Demo中有自定义View CustomView，其内部自定义了几个属性。
为了对其进行换肤，Demo工程中提供了完整的示例代码，具体可参阅CustomViewCompat文件。
