### ISSUE TITLE
这可以上谷歌市场吗

### ISSUE THREAD

**Issue by Gluttony-boop** [CoderAlee/PaintedSkin#54]
做海外app的，已经上架的，引入这个框架，谷歌可以让上吗

**Comment by CoderAlee** [comment]
可以，此框架无恶意代码、安全漏洞或其他安全风险

**Comment by Gluttony-boop** [comment]
Issue found: Violation of Device and Network Abuse policy

Apps that cause users to download or install applications from unknown sources outside of Google Play are prohibited.
Issue details
We found an issue in the following area(s):
Version code 65
被谷歌封了 @CoderAlee

**Comment by CoderAlee** [comment]
是否有具体信息？
此库需要加载外置皮肤包，如果不符合谷歌规则，可以考虑使用RRO来代替库内的皮肤包解析逻辑。
![image](https://github.com/user-attachments/assets/c11454f0-8a6a-43c2-9af8-3f679d9116e8)

**Comment by Gluttony-boop** [comment]
RRO是啥？ @CoderAlee

**Comment by CoderAlee** [comment]
https://source.android.com/docs/core/architecture/rros?hl=zh-cn
https://juejin.cn/post/7262919087175991353 
可以参考这两篇文档

**Comment by Gluttony-boop** [comment]
> https://source.android.com/docs/core/architecture/rros?hl=zh-cn https://juejin.cn/post/7262919087175991353 可以参考这两篇文档

看了，这是系统app才能这样吧，我们直播app根据不好搞
