### ISSUE TITLE
如何动态设置图片之类的，有些第三方view，没有属性，就是代码中设置图片的，如何动态获取皮肤包的图片

### ISSUE THREAD

**Issue by Gluttony-boop** [CoderAlee/PaintedSkin#55]
![微信图片_20241111172509](https://github.com/user-attachments/assets/e38feda4-090a-44e8-8441-3de71755608f)

**Comment by Gluttony-boop** [comment]
![Uploading 微信图片_20241111172509.png…]()

**Comment by CoderAlee** [comment]
1. 可以通过 ThemeSkinService.getInstance().currentThemeSkinPack.getXX主动获取当前皮肤包内的资源。
2. 可以通过WindowManager.getInstance().getWindowProxy(view.context).addEnabledThemeSkinView(view, *skinElement) 的方式，将需要换肤的view 以及需要换肤的属性/函数委托给框架，主题发生变化时，框架会自动调用对应代码进行换肤。

**Comment by Gluttony-boop** [comment]
感谢，大大真的回复及时，最近有发新版本的准备吗？

**Comment by CoderAlee** [comment]
计划用kotlin 重构一版，但最近工作比较忙，进度会比较慢
