### ISSUE TITLE
anr,dialogfragment + viewpager2+ fragment +SwipeRefreshLayout+RecyclerView ，在加载第二页下来刷新时会明显卡顿，其他页正常。

### ISSUE THREAD

**Issue by Gluttony-boop** [CoderAlee/PaintedSkin#57]
time = 706
thread-time = 691
time-start = 11-28 14:21:32.014
time-end = 11-28 14:21:32.720

stack = 11-28 14:21:32.315

java.lang.String.equals(String.java:997)
java.util.Vector.indexOf(Vector.java:408)
java.util.Vector.indexOf(Vector.java:382)
java.util.Vector.removeElement(Vector.java:641)
java.util.Vector.remove(Vector.java:799)
org.alee.component.skin.collection.SparseStack.put(SparseStack.java:44)
org.alee.component.skin.page.ViewWarehouse.addSkinExecutor(ViewWarehouse.java:41)
org.alee.component.skin.page.ViewWarehouse.addEnabledThemeSkinView(ViewWarehouse.java:75)
org.alee.component.skin.page.ViewWarehouse.addEnabledThemeSkinView(ViewWarehouse.java:88)
org.alee.component.skin.factory2.ThemeSkinFactory2.distinguishEnableSkin(ThemeSkinFactory2.java:51)
org.alee.component.skin.factory2.InterceptorFactory2.onReplaceView(InterceptorFactory2.java:48)
org.alee.component.skin.factory2.BaseFactory2.onCreateView(BaseFactory2.java:41)
android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1065)
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
android.view.LayoutInflater.inflate(LayoutInflater.java:686)
android.view.LayoutInflater.inflate(LayoutInflater.java:538)
com.chad.library.adapter.base.BaseQuickAdapter.getItemView(BaseQuickAdapter.java:1639)
com.chad.library.adapter.base.BaseQuickAdapter.createBaseViewHolder(BaseQuickAdapter.java:1140)
com.chad.library.adapter.base.BaseQuickAdapter.onCreateDefViewHolder(BaseQuickAdapter.java:1136)
com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:858)
com.chad.library.adapter.base.BaseQuickAdapter.onCreateViewHolder(BaseQuickAdapter.java:72)
androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7295)
androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:572)
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
android.widget.FrameLayout.onLayout(FrameLayout.java:270)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
android.widget.FrameLayout.onLayout(FrameLayout.java:270)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878)
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChild(ViewGroup.java:6864)
androidx.viewpager2.widget.ViewPager2.onMeasure(ViewPager2.java:498)
android.view.View.measure(View.java:24856)
androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
com.android.internal.policy.DecorView.onMeasure(DecorView.java:775)
android.view.View.measure(View.java:24856)
android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3119)
android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1931)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2225)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
android.view.Choreographer.doCallbacks(Choreographer.java:865)
android.view.Choreographer.doFrame(Choreographer.java:800)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
android.os.Handler.handleCallback(Handler.java:883)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:224)
android.app.ActivityThread.main(ActivityThread.java:7562)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

11-28 14:21:32.616

java.lang.reflect.Array.createObjectArray(Native Method)
java.lang.reflect.Array.newArray(Array.java:776)
java.lang.reflect.Array.newInstance(Array.java:78)
java.util.Arrays.copyOf(Arrays.java:3137)
java.util.Arrays.copyOf(Arrays.java:3106)
androidx.constraintlayout.core.SolverVariable.addToRow(SolverVariable.java:184)
androidx.constraintlayout.core.ArrayLinkedVariables.add(ArrayLinkedVariables.java:330)
androidx.constraintlayout.core.ArrayLinkedVariables.use(ArrayLinkedVariables.java:356)
androidx.constraintlayout.core.ArrayRow.updateFromRow(ArrayRow.java:561)
androidx.constraintlayout.core.ArrayRow.updateFromSystem(ArrayRow.java:734)
androidx.constraintlayout.core.LinearSystem.addConstraint(LinearSystem.java:573)
androidx.constraintlayout.core.LinearSystem.addEquality(LinearSystem.java:1367)
androidx.constraintlayout.core.widgets.Chain.applyChainConstraints(Chain.java:158)
androidx.constraintlayout.core.widgets.Chain.applyChainConstraints(Chain.java:66)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.addChildrenToSolver(ConstraintWidgetContainer.java:445)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:835)
androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
android.view.View.measure(View.java:24856)
androidx.recyclerview.widget.GridLayoutManager.measureChildWithDecorationsAndMargin(GridLayoutManager.java:775)
androidx.recyclerview.widget.GridLayoutManager.measureChild(GridLayoutManager.java:746)
androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:607)
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:625)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
android.widget.FrameLayout.onLayout(FrameLayout.java:270)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
android.widget.FrameLayout.onLayout(FrameLayout.java:270)
android.view.View.layout(View.java:22088)
android.view.ViewGroup.layout(ViewGroup.java:6325)
androidx.recyclerview.widget.RecyclerView$LayoutManager.layoutDecoratedWithMargins(RecyclerView.java:9878)
androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1689)
androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3686)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChild(ViewGroup.java:6864)
androidx.viewpager2.widget.ViewPager2.onMeasure(ViewPager2.java:498)
android.view.View.measure(View.java:24856)
androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
android.view.View.measure(View.java:24856)
android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6893)
android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
com.android.internal.policy.DecorView.onMeasure(DecorView.java:775)
android.view.View.measure(View.java:24856)
android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3119)
android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1931)
android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2225)
android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1819)
android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7783)
android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
android.view.Choreographer.doCallbacks(Choreographer.java:865)
android.view.Choreographer.doFrame(Choreographer.java:800)
android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
android.os.Handler.handleCallback(Handler.java:883)
android.os.Handler.dispatchMessage(Handler.java:100)
android.os.Looper.loop(Looper.java:224)
android.app.ActivityThread.main(ActivityThread.java:7562)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Gluttony-boop** [comment]
开了所有 View 都参与换肤模式

**Comment by CoderAlee** [comment]
可以附上完整的anr trace 文件么？

**Comment by Gluttony-boop** [comment]
上面就是anr 的日志，用滴滴工具抓出来了

**Comment by CoderAlee** [comment]
这个日志看不到anr时整个系统的情况，可以抓一下/data/anr/ 里面记录有anr时整个操作系统的情况。

**Comment by Gluttony-boop** [comment]
搞错了，查清楚了，是SwipeRefreshLayout的问题，不是库的问题
